controllers/common/util.go, controllers/constant/constants.go, controllers/namespacescope_controller.go, main.go
1. Set default restartLabels
2. Update NSS Operator logic: merge all the CRs’ namespaces into the configmap, if they set the same namespace.
3. Add `setDefaults`  for instance during the deletion.
4. role/rolebinding name: namespacescope-managed-role-from-NS-CMNAME
=> multiple CRs managing the same configmap

bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml, bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
1. Remove the `replace` section as it is the origin of v3 channel.
2. add `olm.skipRange: '<1.1.0'` as it supports upgrading from the version smaller than `1.1.0`
=> switch 1.1.0 to v3 channel

bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml, config/crd/bases/operator.ibm.com_namespacescopes.yaml, controllers/namespacescope_controller.go, go.sum, main.go
This PR enabling the namespace scope operator to watch and manage NSS CR from other namespaces.
Then the service from other namespaces can use namespacescope CR to manage their permission scope.
=> feat: make namespace scope operator being able to watch multiple namespace

README.md, bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml, bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/namespacescope_controller.go, deploy/role.yaml, scripts/authorize-namespace.sh
Grant escalate and bind permission to role to make sure NamespaceScope operator can create any roles and create rolebinding for it.
=> Grant escalate and bind permission to create role and rolebinding

controllers/namespacescope_controller.go
Found error during test
```
I0512 19:29:18.418967       1 namespacescope_controller.go:131] Finished reconciling NamespaceScope: cp4i/common-service
I0512 19:29:18.419044       1 namespacescope_controller.go:109] Reconciling NamespaceScope: cp4i/nss-odlm-scope
I0512 19:29:18.694091       1 namespacescope_controller.go:131] Finished reconciling NamespaceScope: cp4i/nss-odlm-scope
E0512 19:29:20.090725       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1508780), concrete:(*runtime._type)(0x165b0c0), asserted:(*runtime._type)(0x167f840), missingMethod:""} (interface conversion: runtime.Object is *v1alpha1.Subscription, not *v1alpha1.ClusterServiceVersion)
goroutine 445 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14f8160, …
```
=> interface conversion error

bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml, bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml, config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml, controllers/common/util.go, controllers/namespacescope_controller.go, main.go
This reverts commit cb1481f38065c6c92795ccc3e2f0ee2ef78fd90c.
Revert this back to the same status as existing LTSR stream for CP4D testing
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>
=> Revert "adopt multiNamespace Installation mode"

Makefile, bundle.Dockerfile, bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/rbac/role.yaml
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60516
Removing wildcard * and explicitly listing out the basic permissions need by NSS operator in its CSV to finish reconciliation
1. Install NSS operator in operator namespace and create nss CR
2. Remove wildcard * and apply basic permission list in CSV
3. Copy the permissions listed from NSS operator CSV, and create a Role with those permissions in a tethered namespace.
4. Bind this Role in the tethered namespace with NSS operator's service account in operator namespace
5. Verify if NamespaceScope operator is able to project it own RBAC, and reconciliation is finished.
=> Keep basic permissions and remove wildcard* in NSS operator CSV

bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/namespacescope_controller.go
- Resolve following errors, this issue could happen on `deployment`, `statefulset` and `daemonset`
```
E1102 00:28:08.507129 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:cs1:ibm-namespace-scope-operator" cannot list resource "deployments" in API group "apps" in the namespace "cs1"
```
- Add cluster permission to [get namespace for `function getValidatedNamespaces()`](https://github.com/IBM/ibm-namespace-scope-operator/blob/ae94063b7be55b2117e08520c3359dc9b9c50b77/controllers/namespacescope_controller.go#L936)
=> Add missing permission for NSS operator

controllers/namespacescope_controller.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/60971
Test image: quay.io/yuchen_shen/nss:label
1. Deploy advanced topologies with NameSpace Scope installed
2. Apply the test image
3. Delete the those roles for  cs-operator, and ODLM
4. Labels added
```
labels:
app.kubernetes.io/instance: namespace-scope
app.kubernetes.io/managed-by: ibm-namespace-scope-operator
app.kubernetes.io/name: common-service
```
=> add labels for role and rolebinding created by NSS

controllers/namespacescope_controller.go
This fix is ​​to solve the problem that the instance name will be updated back and forth into different NSS CRs' names if there are more than one NSS CRs in this cluster, then set the name as `namespace-scope` ConfigMap's name.
=> Set instance name as configmap name

PROJECT, controllers/namespacescope_controller.go, controllers/suite_test.go, go.mod, main.go
https://go.dev/ref/mod#major-version-suffixes
Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version. For example, if a module has the path example.com/mod at v1.0.0, it must have the path example.com/mod/v2 at version v2.0.0.
=> Update go module to match major version v4

bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/manager/manager.yaml
**What this PR does / why we need it**:
add securityContext .ceccompProfile field to pod container
**Which issue(s) this PR fixes**:
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64465
=> add securityContext .seccompProfile field

Dockerfile
Reverts IBM/ibm-namespace-scope-operator#336
Looks like this build worked 2 weeks ago, but there is no ppc or s390 1.23.1-bullseye image now so builds are failing after the version bump. Reverting this temporarily until we can switch to bookworm.
=> Revert "Bump golang from 1.23.0-bullseye to 1.23.1-bullseye"

controllers/common/util.go, controllers/namespacescope_controller.go
What this PR does / why we need it:
k8s label name length limit to 64 characters, so olm will cut off any label longer than 64 characters
We rely on label to find csv and subscription, so we also need to cut of the label if it is longer than 64 characters.
Which issue(s) this PR fixes:
script enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378
=> label length limitation

controllers/namespacescope_controller.go
nss operator also use label to copy and delete RBACs, so we also need to update the label in it
Which issue(s) this PR fixes:
enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378
=> update RBAC with length-limited-label

controllers/namespacescope_controller.go
fix: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65183#issuecomment-95486964
This fix prevents multiple error messages from being sent to the error channel when an error occurs in goroutine for every single service account. By adding an early return, the function will stops execution on the first encountered error, avoiding redundant error handling and keeping the channel from overflowing
=> Add early return in goroutine for each SA

helm/templates/01-operator-deployment.yaml, helm/templates/02-nss-cr.yaml
removed apostrophes around image value because CICD automation removes the closing apostrophe, leading to image pull error because the values looks like `'image:digest`
=> fixed incorrect tetheredNamespace reference

helm/templates/00-rbac.yaml
to use names generated by authorization script because reconcile will look for `nss-managed-role-from-operatorNamespace` before creating configmap
=> fixed helm rbac resource names

Makefile
The current build is missing `release` and `version` label.
```
➜  docker image inspect docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-integration-docker-local/ibmcom/ibm-namespace-scope-operator:4.2.14 | grep "version"
"io.buildah.version": "1.39.0-dev",
"org.label-schema.schema-version": "1.0",
"version": ""
➜  docker image inspect docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-integration-docker-local/ibmcom/ibm-namespace-scope-operator:4.2.14 | grep "release"
"release": "",
```
=> Add RELEASE_VERSION into docker build arg for RH certification

controllers/namespacescope_controller.go, helm/templates/02-nss-cr.yaml
to avoid the issue of stuck terminating CR after helm uninstall
to avoid the issue of CR garbage collected after a helm re-install
=> skip adding finalizer to CR when helm install

common/scripts/lint_go.sh, controllers/namespacescope_controller.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66657
we shouldn't use [reflect.deepequal](https://github.com/IBM/ibm-namespace-scope-operator/blob/master/controllers/namespacescope_controller.go#L1269) to compare two namespace lists because the order might different. This would cause nss operator reconciling forever and will put high strain on api-server as well
=> ignore difference in the order of namesapceList

bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml, version/version.go
What this PR does / why we need it:
Update NSS to 4.2.19 for CS 4.6.19
=> Bump Namespace Scope Operator version to 4.2.19
