- controllers/namespacescope_controller.go
> get the service accounts whose pods are with restartLabels

- controllers/namespacescope_controller.go
fix #6 
and merge master branch
> restart pods after ConfigMap is updated

- controllers/constant/constants.go
- controllers/namespacescope_controller.go
1. Update name of role and rolebinding
2. Check namespace if valid when it has the cluster permission
> Update name of role and rolebinding

- api/v1/namespacescope_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
- controllers/constant/constants.go
- controllers/namespacescope_controller.go
> only copy specific role

- api/v1/namespacescope_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
- controllers/constant/constants.go
- controllers/namespacescope_controller.go
This reverts commit 576c89db5a472b746d2da31a176d716c55949d8d.
> Revert "only copy specific role (#40)"

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
> bump version to 1.0.1

- api/v1/namespacescope_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
- controllers/constant/constants.go
- controllers/namespacescope_controller.go
> add ServiceAccountMembers and copy roles from service account

- controllers/namespacescope_controller.go
Add service account into the name of copied role and rolebinding
> Add service account into the name of copied role and rolebinding

- controllers/namespacescope_controller.go
- scripts/authorize-namespace.sh
enhance the delete logic to update configmap first then delete the roles.
Revert the changes on the authorization script.
> enhance the delete logic

- controllers/namespacescope_controller.go
Set name and namespace when create configmap
> Fix create configmap

- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Update labels
```
beta.kubernetes.io/arch -> kubernetes.io/arch
beta.kubernetes.io/os -> kubernetes.io/os
```
> Use label kubernetes.io

- Dockerfile
> updated golang to 1.15.10 and ubi8 to 8.3-291 to remediate

- config/crd/bases/operator.ibm.com_namespacescopes.yaml
- controllers/namespacescope_controller.go
- go.sum
- Only refresh pods get watch namespace from configmap
- Refresh Operator pods by delete the operator pod
- Refresh Operand pods by rolling update
> fix: apply different strategies to refresh pods

- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- controllers/namespacescope_controller.go
- go.sum
- main.go
This PR is revert because of the security concern. 
Additional cluster permissions are added in the restricted mode
> revert watch CR from all namespace

- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
add deletecollection permission enable to make restricted mode has enough permission to delete all the rbac or pods
> add deletecollection permission

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- controllers/namespacescope_controller.go
Add deletecollection permission into role and cluster role
> Add deletecollection permission into role

- README.md
Add additional clarification on the following:
1.  It's relationship to the Operator SDK, OLM and OperatorGroups.
2. The new csvInjector capability 
3. How to install independently without common services into any Operator namespace.
> Update README.md to include csvInjector info

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
* opt-in of ubi base image automated builds
* configure Docker Credential
> opt-in of ubi base image automated builds (#117)

- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
Hold until release and version bumped
> fix minKubeVersion

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Yuchen Shen <yuchen.shen@mail.utoronto.ca>
> nss version bump to 1.13.2

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: qpdpQ <liyuchen223@gmail.com>
> bump ltsr to 3.19.4

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Ben Luzarraga <luzarragaben@ibm.com>
> bump version for 3.19.6

- common/scripts/next-csv.sh
> updated namespace scope version bump script

- api/v1/namespacescope_types.go
- bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
- bundle/manifests/operator.ibm.com_namespacescopes.yaml
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
This reverts commit 39832d0725deaeb301768a8e83b16ea612a161e4.
> Revert "set value of csvInjector enable to true in nss CR (#187)"

- api/v1/namespacescope_types.go
- bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
- bundle/manifests/operator.ibm.com_namespacescopes.yaml
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
Reverts IBM/ibm-namespace-scope-operator#189
> Revert "[release-ltsr] set value of csvInjector enable to true in nss CR"

- api/v1/namespacescope_types.go
- bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
- bundle/manifests/operator.ibm.com_namespacescopes.yaml
- config/crd/bases/operator.ibm.com_namespacescopes.yaml
> marker used to annotate presered unnknown field

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: qpdpQ <liyuchen223@gmail.com>
> bump version for 3.19.7

- Makefile
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>
> Remove quay.io registry when building the image

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: qpdpQ <liyuchen223@gmail.com>
> bump cd to 3.23

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Ben Luzarraga <luzarragaben@ibm.com>
> bump version for 3.19.8

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
> new artifactory image endpoint (namespace scope)

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
> [ltsr] new artifactory image endpoint (namespace scope)

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
> [future] new artifactory image endpoint (namespace scope)

- Makefile
- bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
- bundle-restricted/metadata/annotations.yaml
- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>
> reduce permission for future NSS operator

- common/config/.golangci.yml
- controllers/common/util.go
- controllers/namespacescope_controller.go
fix for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58091#issuecomment-55546849
we should ignore the role for nss operator itself it in all namespaces
> Ignore all ns

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58764
> [NSS LTSR] "disconnected" annotation for certification assessment

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680
> Update ImagePullPolicy to IfNotPresent

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58763
> [Bedrock 4.1 NSS] "disconnected" annotation for certification assessment

- controllers/common/util.go
- controllers/namespacescope_controller.go
> [LTSR] Handle NamespaceScope ENV Variable Patching issue  (#258)

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59738
> add ephemeral-storage request to container

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59790
> Add the common label to the operand Deployment/Pod

- controllers/namespacescope_controller.go
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60517
The user do not want to grant full namespace admin permission in each tenant namespace, we remove the admin auth check  function in each namespace
1. install NSS operator in a `nss-reduction` namespace
2. only create Role `nss-managed-role-from-nss-reduction` and RoleBinding in `nss-cp` and including one rule
```
rules:
- verbs:
- create
- delete
- get
- list
- patch
- update
- watch
- deletecollection
apiGroups:
- app
resources:
- deployments
```
3. From nss pod log:
```
I1006 20:20:17.294505 1 namespacescope_controller.go:134] Reconciling NamespaceScope: nss-reduction/common-service
I1006 20:20:17.297260 1 namespacescope_controller.go:1029] ibm-namespace-scope-operator doesn't have admin permission in namespace nss-cp …
```
> remove namespace admin auth check

- controllers/namespacescope_controller.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60521
After NSS operator remove its wildcard permission in tethered namespace, it does not have sufficient permissions to do RBAC projection for ODLM, because ODLM contains wildcard permission in its CSV and NSS operator will try to copy this wildcard permission to tethered namespace.
As a result, NSS operator would still do the RBAC projection for the permissions which are required by ODLM AND are granted by NSS operator - a subset of permissions that ODLM needs and NSS has.
Therefore, ODLM will keep wildcard permission in original operator namespace, and be granted the same permission as NSS operator in tethered namespace.
1. Deploy 4.3 Dev build in simple topology under namespace `nss-test`
2. Manually deploy NSS operator in …
> Bind NSS roles' permission to the operator which contains wildcard in apiGroups or Resources

- controllers/namespacescope_controller.go
- unsure how there were no errors before since value was never set globally
> removed global context from controller

- controllers/namespacescope_controller.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64680
The code has been enhanced to run the RBAC generation in different namespaces concurrently, the process now ensures that failures in one namespace do not block RBAC generation in other namespaces, while still returning an error if any occur.
- Introduced a `sync.WaitGroup` to ensure all RBAC generation tasks are completed before proceeding, regardless of success or failure in individual namespaces.
- Added error handling with an `error channel` to capture any failures during RBAC generation in a namespace.
image: quay.io/yuchen_shen/nss:rbac
1. Using events operator as a test example, and remove some events operator permission for resources [`kafkatopics, kafkatopics/status, kafkausers, kafkausers/status`]
2. Request to …
> Perform the RBAC propagation in parallel across namespaces

- controllers/namespacescope_controller.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65348
> Update the label of NSS role

- bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
- config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
..as defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification
> Add required OLM metadata

- helm-cluster-scoped/Chart.yaml
- helm-cluster-scoped/templates/00-crd.yaml
- helm-cluster-scoped/templates/01-cluster-rbac.yaml
- helm-cluster-scoped/values.yaml
- helm/Chart.yaml
- helm/templates/00-rbac.yaml
- helm/templates/01-operator-deployment.yaml
- helm/templates/02-nss-cr.yaml
- helm/values.yaml
Definitely missing some things still, like changing the image value to be constructed via values.yaml
> Add helm chart for no olm work

- helm-cluster-scoped/Chart.yaml
- helm/templates/01-operator-deployment.yaml
- helm/values.yaml
update imagetag and add operatorImage variable
> update image tag and chart name

- controllers/namespacescope_controller.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66500
> add warnning message if NSS operator unable to patch CSV
